backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}/{{month}}/{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }

  - name: "micro"
    label: "Microblog"
    folder: "src/pages/micro"
    create: true
    slug: "{{year}}/{{month}}/{{slug}}"
    identifier_field: body
    fields:
      - label: "Template Key"
        name: templateKey
        widget: hidden
        default: microblog-post
      - { label: "Publish Date", name: date, widget: datetime }
      - { label: Path, name: path, widget: string }
      - { label: Body, name: body, widget: markdown }

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "static-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/talks/index.md"
        label: "Talks"
        name: "talks"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "static-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/music/index.md"
        label: "Music"
        name: music
        fields:
          - { label: "Template Key", name: templateKey, widget: hidden, default: music-page }
          - { label: "Title", name: title, widget: string }
          - { label: "Body", name: body, widget: markdown }
          - label: "Albums"
            name: albums
            widget: list
            fields:
              - { label: "Name", name: name, widget: string }
              - { label: "Artist", name: artist, widget: string }
              - { label: "Link", name: url, widget: string }
              - { label: "Image", name: image, widget: image, allow_multiple: false }
